// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/exchange/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/ibc-go/v6/modules/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgTeleport defines a msg to telefort fungible tokens (i.e Coins) between
// ICS20 enabled chains through intermediary chain.
// Built for the purpose of transferring the coins with custom data that can be used in the intermediary chain.
// The intermediary chain should enable the token swap and transfer to the destination chain.
type MsgTeleport struct {
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty" yaml:"source_port"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,2,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty" yaml:"source_channel"`
	// the tokens to be transferred
	Token types.Coin `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	// the sender address
	Sender string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	// the recipient address on the destination chain
	Receiver string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Timeout height relative to the current block height.
	// The timeout is disabled when set to 0.
	TimeoutHeight types1.Height `protobuf:"bytes,6,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height" yaml:"timeout_height"`
	// Timeout timestamp in absolute nanoseconds since unix epoch.
	// The timeout is disabled when set to 0.
	TimeoutTimestamp uint64 `protobuf:"varint,7,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty" yaml:"timeout_timestamp"`
	// optional memo
	Memo string `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	// optional args
	Args []string `protobuf:"bytes,9,rep,name=args,proto3" json:"args,omitempty"`
}

func (m *MsgTeleport) Reset()         { *m = MsgTeleport{} }
func (m *MsgTeleport) String() string { return proto.CompactTextString(m) }
func (*MsgTeleport) ProtoMessage()    {}
func (*MsgTeleport) Descriptor() ([]byte, []int) {
	return fileDescriptor_18d161a1c7fd5df0, []int{0}
}
func (m *MsgTeleport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTeleport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTeleport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTeleport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTeleport.Merge(m, src)
}
func (m *MsgTeleport) XXX_Size() int {
	return m.Size()
}
func (m *MsgTeleport) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTeleport.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTeleport proto.InternalMessageInfo

// MsgTeleportResponse defines the Msg/Teleport response type.
type MsgTeleportResponse struct {
	// sequence number of the teleport packet sent
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgTeleportResponse) Reset()         { *m = MsgTeleportResponse{} }
func (m *MsgTeleportResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTeleportResponse) ProtoMessage()    {}
func (*MsgTeleportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18d161a1c7fd5df0, []int{1}
}
func (m *MsgTeleportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTeleportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTeleportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTeleportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTeleportResponse.Merge(m, src)
}
func (m *MsgTeleportResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTeleportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTeleportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTeleportResponse proto.InternalMessageInfo

func (m *MsgTeleportResponse) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgTeleport)(nil), "ibc.applications.exchange.v1.MsgTeleport")
	proto.RegisterType((*MsgTeleportResponse)(nil), "ibc.applications.exchange.v1.MsgTeleportResponse")
}

func init() {
	proto.RegisterFile("ibc/applications/exchange/v1/tx.proto", fileDescriptor_18d161a1c7fd5df0)
}

var fileDescriptor_18d161a1c7fd5df0 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xb6, 0xff, 0xa4, 0xf9, 0xd3, 0x8d, 0x5a, 0xc1, 0x02, 0x95, 0x1b, 0x15, 0x3b, 0xb2, 0x84,
	0x14, 0x0e, 0xec, 0xca, 0x45, 0x50, 0xa9, 0x27, 0x94, 0x5e, 0xe0, 0x50, 0x09, 0xac, 0x9e, 0xb8,
	0x14, 0x7b, 0x3b, 0x72, 0x56, 0xd8, 0x1e, 0xe3, 0xdd, 0x44, 0xed, 0x1b, 0x70, 0xe4, 0x11, 0xfa,
	0x38, 0x3d, 0x56, 0x9c, 0x38, 0x45, 0x28, 0xb9, 0x70, 0xce, 0x13, 0xa0, 0xb5, 0x9d, 0x90, 0x5c,
	0x10, 0x27, 0xcf, 0xf7, 0xcd, 0x37, 0xfe, 0x76, 0x76, 0x66, 0xc9, 0x33, 0x19, 0x0b, 0x1e, 0x15,
	0x45, 0x2a, 0x45, 0xa4, 0x25, 0xe6, 0x8a, 0xc3, 0xb5, 0x18, 0x47, 0x79, 0x02, 0x7c, 0x1a, 0x70,
	0x7d, 0xcd, 0x8a, 0x12, 0x35, 0xd2, 0x23, 0x19, 0x0b, 0xb6, 0x29, 0x63, 0x2b, 0x19, 0x9b, 0x06,
	0xfd, 0xc7, 0x09, 0x26, 0x58, 0x09, 0xb9, 0x89, 0xea, 0x9a, 0xbe, 0x2b, 0x50, 0x65, 0xa8, 0x78,
	0x1c, 0x29, 0xf3, 0xb3, 0x18, 0x74, 0x14, 0x70, 0x81, 0x32, 0x6f, 0xf2, 0x9e, 0xb1, 0x16, 0x58,
	0x02, 0x17, 0xa9, 0x84, 0x5c, 0x1b, 0xc3, 0x3a, 0xaa, 0x05, 0xfe, 0xf7, 0x16, 0xe9, 0x9d, 0xab,
	0xe4, 0x02, 0x52, 0x28, 0xb0, 0xd4, 0xf4, 0x84, 0xf4, 0x14, 0x4e, 0x4a, 0x01, 0x97, 0x06, 0x3a,
	0xf6, 0xc0, 0x1e, 0xee, 0x8e, 0x0e, 0x96, 0x33, 0x8f, 0xde, 0x44, 0x59, 0x7a, 0xea, 0x6f, 0x24,
	0xfd, 0x90, 0xd4, 0xe8, 0xbd, 0x29, 0x7c, 0x43, 0xf6, 0x9b, 0x9c, 0x39, 0x73, 0x0e, 0xa9, 0xf3,
	0x5f, 0x55, 0x7b, 0xb8, 0x9c, 0x79, 0x4f, 0xb6, 0x6a, 0x9b, 0xbc, 0x1f, 0xee, 0xd5, 0xc4, 0x59,
	0x8d, 0xe9, 0x2b, 0xb2, 0xa3, 0xf1, 0x33, 0xe4, 0x4e, 0x6b, 0x60, 0x0f, 0x7b, 0xc7, 0x87, 0xac,
	0xee, 0x8d, 0x99, 0xde, 0x58, 0xd3, 0x1b, 0x3b, 0x43, 0x99, 0x8f, 0xda, 0x77, 0x33, 0xcf, 0x0a,
	0x6b, 0x35, 0x3d, 0x20, 0x1d, 0x05, 0xf9, 0x15, 0x94, 0x4e, 0xdb, 0x18, 0x86, 0x0d, 0xa2, 0x7d,
	0xd2, 0x2d, 0x41, 0x80, 0x9c, 0x42, 0xe9, 0xec, 0x54, 0x99, 0x35, 0xa6, 0x9f, 0xc8, 0xbe, 0x96,
	0x19, 0xe0, 0x44, 0x5f, 0x8e, 0x41, 0x26, 0x63, 0xed, 0x74, 0x2a, 0xcf, 0x3e, 0x33, 0x33, 0x30,
	0xf7, 0xc5, 0x9a, 0x5b, 0x9a, 0x06, 0xec, 0x6d, 0xa5, 0x18, 0x3d, 0x35, 0xa6, 0x7f, 0x9a, 0xd9,
	0xae, 0xf7, 0xc3, 0xbd, 0x86, 0xa8, 0xd5, 0xf4, 0x1d, 0x79, 0xb8, 0x52, 0x98, 0xaf, 0xd2, 0x51,
	0x56, 0x38, 0xff, 0x0f, 0xec, 0x61, 0x7b, 0x74, 0xb4, 0x9c, 0x79, 0xce, 0xf6, 0x4f, 0xd6, 0x12,
	0x3f, 0x7c, 0xd0, 0x70, 0x17, 0x2b, 0x8a, 0x52, 0xd2, 0xce, 0x20, 0x43, 0xa7, 0x5b, 0x35, 0x51,
	0xc5, 0x86, 0x8b, 0xca, 0x44, 0x39, 0xbb, 0x83, 0x96, 0xe1, 0x4c, 0x7c, 0xda, 0xfd, 0x7a, 0xeb,
	0x59, 0xbf, 0x6e, 0x3d, 0xcb, 0x0f, 0xc8, 0xa3, 0x8d, 0x99, 0x86, 0xa0, 0x0a, 0xcc, 0x15, 0x98,
	0x1b, 0x51, 0xf0, 0x65, 0x02, 0xb9, 0x80, 0x6a, 0xb0, 0xed, 0x70, 0x8d, 0x8f, 0x91, 0xb4, 0xce,
	0x55, 0x42, 0xc7, 0xa4, 0xbb, 0x5e, 0x85, 0xe7, 0xec, 0x6f, 0x0b, 0xc9, 0x36, 0x1c, 0xfa, 0xc1,
	0x3f, 0x4b, 0x57, 0x87, 0x19, 0x7d, 0xb8, 0x9b, 0xbb, 0xf6, 0xfd, 0xdc, 0xb5, 0x7f, 0xce, 0x5d,
	0xfb, 0xdb, 0xc2, 0xb5, 0xee, 0x17, 0xae, 0xf5, 0x63, 0xe1, 0x5a, 0x1f, 0x4f, 0x12, 0xa9, 0xc7,
	0x93, 0x98, 0x09, 0xcc, 0x78, 0xb3, 0xde, 0x32, 0x16, 0x2f, 0x12, 0xe4, 0xd3, 0xd7, 0x3c, 0xc3,
	0xab, 0x49, 0x0a, 0xca, 0x3c, 0xa7, 0x8d, 0x67, 0xa4, 0x6f, 0x0a, 0x50, 0x71, 0xa7, 0x5a, 0xe9,
	0x97, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x95, 0xb9, 0x39, 0xd0, 0x70, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Teleport defines a rpc handler method for MsgTeleport.
	Teleport(ctx context.Context, in *MsgTeleport, opts ...grpc.CallOption) (*MsgTeleportResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Teleport(ctx context.Context, in *MsgTeleport, opts ...grpc.CallOption) (*MsgTeleportResponse, error) {
	out := new(MsgTeleportResponse)
	err := c.cc.Invoke(ctx, "/ibc.applications.exchange.v1.Msg/Teleport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Teleport defines a rpc handler method for MsgTeleport.
	Teleport(context.Context, *MsgTeleport) (*MsgTeleportResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Teleport(ctx context.Context, req *MsgTeleport) (*MsgTeleportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Teleport not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Teleport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTeleport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Teleport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.applications.exchange.v1.Msg/Teleport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Teleport(ctx, req.(*MsgTeleport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.applications.exchange.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Teleport",
			Handler:    _Msg_Teleport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/applications/exchange/v1/tx.proto",
}

func (m *MsgTeleport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTeleport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTeleport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Args) > 0 {
		for iNdEx := len(m.Args) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Args[iNdEx])
			copy(dAtA[i:], m.Args[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Args[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x42
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Token.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTeleportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTeleportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTeleportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sequence != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTeleport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Token.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TimeoutHeight.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgTeleportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sequence != 0 {
		n += 1 + sovTx(uint64(m.Sequence))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTeleport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTeleport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTeleport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTeleportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTeleportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTeleportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
